### ISSUE TITLE
Architecture errors using docker-compose

### ISSUE THREAD

**Issue by marmata** [akashpandey/Reddit-Fetch#4]
Hi! 

Wat trying to use the docker compose to run the software. Did the token generation already which went fine. However it looks like there's not docker image built for amd64? This is the compose I'm using:

```
version: '3.8'
services:
  reddit-fetcher:
    image: pandeyak/reddit-fetcher:latest  # Use prebuilt image
    container_name: reddit-fetcher
    environment:
      - OUTPUT_FORMAT=html
      - FORCE_FETCH=false
      - FETCH_INTERVAL=86400
    volumes:
      - ./data:/data
    restart: unless-stopped
```
And  the error that I get:
$ sudo docker compose up -d
```
$ sudo docker compose up -d
[sudo] password for marmata:
[+] Running 9/9
 ✔ reddit-fetcher Pulled                                                                                                 6.9s
   ✔ 6e771e15690e Pull complete                                                                                          0.8s
   ✔ b60a29b5b291 Pull complete                                                                                          1.1s
   ✔ 73ab298ef089 Pull complete                                                                                          2.2s
   ✔ c1472cb2a7c8 Pull complete                                                                                          2.2s
   ✔ 9803423a4d0e Pull complete                                                                                          2.3s
   ✔ 5ef0e0e2491d Pull complete                                                                                          2.3s
   ✔ d0d06ecfa121 Pull complete                                                                                          4.3s
   ✔ 96430abf1e3f Pull complete                                                                                          5.2s
[+] Running 2/3
 ✔ Network reddit-fetch_default       Created0.1s                                                                        0.0s
! reddit-fetcher The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v1) and no specific platform was requested 0.0s

```
